# Disks sub-service tspconfig.yaml for v2 folder structure testing
parameters:
  "service-dir":
    default: "sdk/contosodisks"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/../.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/Microsoft.Contoso/ComputeService/Disks/{version-status}/{service-version}/disks.json"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/contosodisks"
    emitter-output-dir: "{output-dir}/{service-dir}/armcontosodisks"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armcontosodisks"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
